"""empty message

Revision ID: 08feea731b10
Revises: 800401bc0a21
Create Date: 2025-06-11 21:33:58.922916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08feea731b10'
down_revision: Union[str, None] = '800401bc0a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimate_info', sa.Column('project_code_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'estimate_info', 'project_code', ['project_code_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'estimate_info', type_='foreignkey')
    op.drop_column('estimate_info', 'project_code_id')
    # ### end Alembic commands ###
