"""empty message

Revision ID: 110386c118c2
Revises: 84dd0e08e3e6
Create Date: 2025-06-11 17:52:13.440846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '110386c118c2'
down_revision: Union[str, None] = '84dd0e08e3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
