"""empty message

Revision ID: 4d423b0698c1
Revises: 461483858128
Create Date: 2025-06-08 22:58:59.592748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4d423b0698c1'
down_revision: Union[str, None] = '461483858128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_name', sa.String(length=255), nullable=False))
    op.drop_column('company', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('company', 'company_name')
    # ### end Alembic commands ###
