"""empty message

Revision ID: 800401bc0a21
Revises: 110386c118c2
Create Date: 2025-06-11 20:08:40.959607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800401bc0a21'
down_revision: Union[str, None] = '110386c118c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_code', sa.Column('status_code', sa.Enum('NOT_STARTED', 'STARTED', 'DONE', name='projectcodestatusenum'), nullable=False))
    op.add_column('project_code', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_code', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_code', sa.Column('tartge_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_code', sa.Column('memo', sa.String(length=750), nullable=True))
    op.add_column('vendor_code', sa.Column('used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_code', 'used_at')
    op.drop_column('project_code', 'memo')
    op.drop_column('project_code', 'tartge_end_date')
    op.drop_column('project_code', 'end_date')
    op.drop_column('project_code', 'start_date')
    op.drop_column('project_code', 'status_code')
    # ### end Alembic commands ###
