"""empty message

Revision ID: ba05f2b40090
Revises: 4d423b0698c1
Create Date: 2025-06-09 02:19:48.277499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba05f2b40090'
down_revision: Union[str, None] = '4d423b0698c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('mfa_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('is_verified_mfa', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'refresh_token')
    op.drop_column('user', 'is_verified_mfa')
    op.drop_column('user', 'mfa_token')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
