version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ../docker/production.Dockerfile
    container_name: carbon-prod
    env_file:
      - ../env/.env
      - ../env/.env.production
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: mysql:8.0
    container_name: mysql-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql

volumes:
  mysql_data_prod:


# 실서버 환경에서는 볼륨 바인딩 제거, --reload 제거
# 민감 정보는 .env.production 또는 AWS Secrets Manager로 관리